[install]
linker = "hoisted"
[workspace]
members = [
  "packages/site",
  "packages/cv",
  "packages/undeploy",
  "test/site",
  "test/cv"
]
[test]
root = "./test"
preload = [
  "./test/setup/happydom.ts",
  "./test/setup/testing-library.ts",
  "./test/setup/bun-test.d.ts"
]
